name: CI

on:
  workflow_dispatch:
    inputs:
      Main:
        type: boolean
        default: false
        required: true
        description: Main
      Internal:
        type: boolean
        description: Internal
        default: false
      
jobs:
  build:
    runs-on: ubuntu-latest
    environment: WARMUP
    strategy:
      matrix:
        app: 
          - ${{ vars.HEROKU_MAIN }} 
          - ${{ vars.HEROKU_INTERNAL }} 
    steps: 
      - uses: actions/checkout@v2
      - name: Deploy main
        if: ${{ inputs.Main }} == true && matrix.app == ${{ vars.HEROKU_MAIN }}
        run: |
          echo ${{ matrix.index }}
          echo "Deploying to main"
      - name: Deploy Internal
        if: ${{ inputs.Internal }} == true && matrix.app == ${{ vars.HEROKU_INTERNAL }}
        run: |
          echo ${{ matrix.index }}
          echo "Deploying to Internal"
        
      

#     steps:
#       - uses: actions/checkout@v2
#       - name: greet
#         run: |
#           echo "Main"  ${{ inputs.Main }} 
#           echo "Internal"  ${{ inputs.Internal }} 
#           echo ${{ vars.MAIN }}
#           echo "MAIN_URL ${{ vars.MAIN.HEROKU_URL }}" 
#       - name: Main
#         if: ${{ inputs.Main }}
#         run: echo ${{ vars.HEROKU_MAIN }}
#       - name: Internal
#         if: ${{ inputs.Internal }}
#         run: echo ${{ vars.HEROKU_INTERNAL }}
        
