name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
      choice:
        type: multi-choice
        description: Make a choice
        options:
        - web
        - cron
        - worker
jobs:
  build:
    runs-on: ubuntu-latest
    environment: WARMUP

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}" / ${{ inputs.boolean }} 
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
          echo "accessing env ${{ env.HEROKU_MAIN }}"
