name: CI

on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    environment: WARMUP

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "URL: ${{ env.HEROKU_MAIN }}"
      - name: List Environment Variables
        run: |
          env
