name: CI

on:
  workflow_dispatch:
    inputs:
       choice:
        type: choice
        description: Make a choice
        options: |
              "option1",
              "option2",
              "option3",
              "-"
              "all"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: WARMUP

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
          echo "URL: ${{ vars.HEROKU_MAIN }}"
